### ISSUE TITLE
`project.scripts` not made available as binaries in the devShell

### ISSUE THREAD

**Issue by silky** [nix-community/pyproject.nix#67]
I'm not sure if it's intended to do so, but I note that if you have a `[project.scripts]` section like so:

```toml
[project.scripts]
foo = "foo.cli:main"
```

then the `foo` executable is not made available when you enter the devShell. It _does_ get created if you `nix build .` the package; but I had hoped it would be available in the shell too!

Is this something we can get working somehow?

**Comment by adisbladis** [comment]
This is semi-intended.
To make scripts available in the development shell we'd have to set them up on `$PATH` _somewhere_, this implies creating a package.

Poetry2nix has a utility function to do this transformation: https://github.com/nix-community/poetry2nix/blob/master/shell-scripts.nix.
That utility function would have to be added to somewhere. I'd prefer it if it was added to nixpkgs rather than here.

**Comment by adisbladis** [comment]
Implementation note:
https://github.com/nix-community/poetry2nix/blob/e31b5e4/shell-scripts.nix#L18-L19 is a hack to achieve loading a local path.
This should probably be solved with an editable install instead if mutable behaviour is desired.

Related issue: https://github.com/nix-community/pyproject.nix/issues/114

**Comment by adisbladis** [comment]
See https://github.com/NixOS/nixpkgs/pull/339228
